# Header details
organisation_name: Digital Shared Services
team_name: Enterprise and Solution Architecture

# Links to show on right-hand-side of header
header_links:
  NICS EA Principles: https://principles.ea.digitalni.gov.uk
  #Citizen Services Architecture: https://docs.ea.digitalni.gov.uk
  GitHub: https://github.com/dof-dss/architecture-blog

# Blog title
blog_title: Enterprise and Solution Architecture Team

# breadcrumb root
blog_root: Architecture Team Blog
