# Header details
organisation_name: NICS Digital Shared Services
team_name: Enterprise and Solution Architecture

# Links to show on right-hand-side of header
header_links:
  NICS EA Principles: https://nics-ea-principles.london.cloudapps.digital
  #Citizen Services Architecture: https://docs.ea.digitalni.gov.uk
  GitHub: https://github.com/dof-dss/architecture-blog

# Blog title
blog_title: Enterprise and Solution Architecture Team
