# Header details
organisation_name: Digital Shared Services
team_name: Enterprise and Solution Architecture Team

# Links to show on right-hand-side of header
header_links:
  About: /
  Blog: /blog/
  Catalogue: /catalogue/
  Support: /support/

# Blog title
blog_title: Architecture Team Blog

# Catalogue product page URLs
catalogue:
  api_management_product_page: https://api-management-product-page.london.cloudapps.digital
  usage_tracking_product_page:
  doc_config_product_page:
  audit_service_product_page:
  customer_identity_hub_product_page:
  employee_identity_hub_product_page:
